name: Build Unity Project (Ubuntu)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Project/Library
          key: Library-StandaloneWindows64
          restore-keys: Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Project
          unityVersion: 6000.2.8f1
          targetPlatform: StandaloneWindows64

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-Windows
          path: Project/build/StandaloneWindows64
